# Generated by Django 3.1.2 on 2020-11-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='acceptance',
            field=models.BooleanField(default=True),
        ),
    ]
