# Generated by Django 3.1.2 on 2020-11-28 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20201127_1911'),
        ('contacts', '0003_auto_20201128_0204'),
    ]

    operations = [
    ]
