# Generated by Django 3.1.2 on 2020-11-28 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_logo'),
        ('customers', '0003_auto_20201128_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_customer_contacts', to='company.company'),
            preserve_default=False,
        ),
    ]
