# Generated by Django 3.1.2 on 2020-11-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_active'),
        ('catalog', '0002_auto_20201106_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_categories', to='company.company'),
            preserve_default=False,
        ),
    ]
