# Generated by Django 3.1.2 on 2020-11-13 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.CharField(max_length=100)),
                ('initial_status', models.CharField(max_length=25)),
                ('final_status', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_changes', to='orders.order')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
